# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Customer')),
                ('slug', models.CharField(max_length=32, verbose_name=b'Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name=b'Domain')),
                ('exact', models.BooleanField(default=True, verbose_name=b'Exact')),
                ('enabled', models.BooleanField(default=True, verbose_name=b'Enabled')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'app', max_length=100, verbose_name=b'Server name')),
                ('address', models.CharField(max_length=100, verbose_name=b'Server address')),
                ('check', models.BooleanField(default=True, verbose_name=b'Check')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[(b'tcp', b'TCP'), (b'http', b'HTTP')], default=b'http', max_length=4, verbose_name=b'Mode')),
                ('enabled', models.BooleanField(default=True, verbose_name=b'Enabled')),
                ('enable_http', models.BooleanField(default=True, help_text=b'Enables the site to be served on the HTTP frontend.', verbose_name=b'Enable HTTP')),
                ('enable_https', models.BooleanField(default=True, help_text=b'Enables the site to be served on the HTTPS frontend.', verbose_name=b'Enable HTTPS')),
                ('force_https', models.BooleanField(default=True, help_text=b'Redirects the user to the HTTPS website when enabled.', verbose_name=b'Force HTTPS')),
                ('enable_sts', models.BooleanField(default=True, help_text=b'Security measurement. This will force browsers to use HTTPS on this site.', verbose_name=b'Enable STS')),
                ('enable_letsencrypt', models.BooleanField(default=True, help_text=b'HTTP and HTTP mode must be enabled for this site in order for LetsEncrypt to work.', verbose_name=b'Enable LetsEncrypt')),
                ('custom_configs', models.TextField(blank=True, null=True, verbose_name=b'Custom backend config')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_list', to='config.Site'),
        ),
        migrations.AddField(
            model_name='domain',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_list', to='config.Site'),
        ),
    ]
